### ISSUE TITLE
한줄평 없을때, 높이 안맞는거 수정 필요

### ISSUE THREAD

**Issue by wjdqlsdlsp** [Sejong-Talk-With/Semogong#1]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/61408680/163662036-ad155e32-65ad-43dc-876b-18255d46b1a6.png">

현재 한줄평 없으면 높이가 안맞습니다. 수정 필요합니다.

**Comment by dlwogns1205** [comment]
노션처럼 하려면 먼저 몇줄에 표현할건지 정하고
max-width 
overflow : hidden

**Comment by dlwogns1205** [comment]
branch : front
commit -m : version#1
제목,한줄평에 고정 height 값 설정
