### ISSUE TITLE
시간 수정도 하게 하는 것 이 좋을 것 같습니다.

### ISSUE THREAD

**Issue by wjdqlsdlsp** [Sejong-Talk-With/Semogong#14]
end 누르고 다시 공부 시작할 수 도있으니 이 것도 같이 해보죠

**Comment by bob8dod** [comment]
몇시든 간에 
	- firts of all : 최신 글이 해당 날짜에 작성한 글인지 판단
	   - yes : 그 글 이어작성
	    - no 
	     1. 현재 시점이 4시 이후
		 - 새글 작성
	     2. 현재 시점이 4시 이전
		 - 그 전날 작성한 글이 존재하는 지 확인
		   - yes : 해당 글 이어 작성
		   - no : 새글 작성

해당 로직으로 수행해 봤습니다. 혹시나 또 오류가 생긴다면 이슈에 남겨주세요.
