### ISSUE TITLE
댓글 입력시 현재 모달에 유지 필요

### ISSUE THREAD

**Issue by wjdqlsdlsp** [Sejong-Talk-With/Semogong#2]
이건 열심히 하고 있는걸로 아는데 해결해봅시당

**Comment by dlwogns1205** [comment]
button에 onclick 함수 만들어서 자바스크립트 함수처리 하는 것도 가능할 것 같음.

**Comment by wjdqlsdlsp** [comment]
댓글 뿐만 아니라, Edit 도 모달에 머무를수 있도록 해주세욤
