### ISSUE TITLE
작성된 날짜 표기

### ISSUE THREAD

**Issue by bob8dod** [Sejong-Talk-With/Semogong#24]
위치를 어디다가 둘지 고민해봐야 될 것 같네요. 의견 주세요.

**Comment by dlwogns1205** [comment]
모달 왼쪽 상단이 좋을 것 같습니다.

**Comment by bob8dod** [comment]
post 좌상단에 나올 수 있도록 설정했습니다.
모달은 따로 넣지 않았습니다.
혹시 모달에도 넣고자 한다면 Issue 남겨 주세요.
