### ISSUE TITLE
포스트 이미지 설정

### ISSUE THREAD

**Issue by wjdqlsdlsp** [Sejong-Talk-With/Semogong#28]
![image](https://user-images.githubusercontent.com/61408680/164148697-633369eb-cdd5-46d0-b2b6-27aacd202a8d.png)

이거 상당히 잘되어있는데 여기에 추가로 이미지도 그냥 보여주죠 용량 얼마안되서 딜레이는 별로 없을것 같은데

**Comment by bob8dod** [comment]
이건 front까지 완벽히 완료되면 close 하겠습니다
