### ISSUE TITLE
로그인 안 된 상태에서 댓글 입력시 에러

### ISSUE THREAD

**Issue by wjdqlsdlsp** [Sejong-Talk-With/Semogong#7]
로그인 안 된 상태에서 댓글 입력시 에러가 발생하네요.
로그인 안 된 상태에서 댓글 입력하면 로그인이 필요합니다 등 경고 띄어서 로그인창으로 이동하게 하죠

**Comment by bob8dod** [comment]
해결했습니다. 
로그인 없이 댓글을 달면 alert 경고창이 뜨도록 설정했습니다.
