### ISSUE TITLE
에러 페이지 생성

### ISSUE THREAD

**Issue by wjdqlsdlsp** [Sejong-Talk-With/Semogong#8]
에러가 많이 나오는거 같은데 에러페이지 하나 만들죠. Whitelabel Error Page 그만보고 싶네요.

**Comment by bob8dod** [comment]
- 해결
    - Spring에서는 자동으로 에러페이지를 연결하는 기능이 있으며, 그 기능을 이용
    - templates/error/4xx.html → 400, 404 등 Error Code가 4로 시작하는 에러들에 대해 해당 html로 연결
    - templates/error/5xx.html → 500, 505 등 Error Code가 5로 시작하는 에러들에 대해 해당 html로 연결
    - templates/error.html → 기본 에러페이지. 위의 해당되지 않는 Error Code들에 대해 연결
    - 고로 해당 html 파일을 사용자친화적으로 만들어 해당 규칙에 맞게 설정.
