### ISSUE TITLE
새글 작성 오류

### ISSUE THREAD

**Issue by potential1205** [Sejong-Talk-With/Semogong#90]
제목을 반드시 작성하도록 알림 및 설정

**Comment by bob8dod** [comment]
현재 post edit과 new post 기능의 html을 공유하고 있고

이전 post edit 시 발생하는 오류에서 

1. simpleMDE가 다른 post의 content에 생성됨 (postEditForm의 content가 unique id가 아니면서 생기는 문제. → edit하면 여러개의 content가 생성되고, 중복된 ID로 인해서 가장 처음 생성된 content에 simpleMDE가 발생)
2. submit 하면 이전에 열었던 post에 fragment가 replacement되고 현재 post는 replacement되지 않음 (postEditForm의 postEdit_container의 id가 unique하지 않아 발생하는 문제, 2번과 동일한 이유로 발생하는 문제)

해당 변경점들을 post new javascript에 반영하지 않아 발생한 문제

**Comment by bob8dod** [comment]
- 해결
    - 기존의 content 라는 id를 가졌던 요소에 content + ${[post.id](http://post.id/)} 의 id를 새로 부여 → 이제 해당 id로 Simple MDE 를 심어줄 수 있음
    - simplemde + ${[post.id](http://post.id/)} 의 변수를 생성해주고 해당 변수에 새로 생성된 Simple MDE 를 할당 → 해당 MDE의 value(content) 를 가져올 수 있게 됨
